version: "3.3"
services:
    mongo:
        image: mongo
        ports:
            - "27018:27017"
        command: mongod

    api:
      image: node:10
      user: "node"
      working_dir: /usr/src/app
      expose:
        - "3007"
      environment:
        - NODE_ENV=development
      volumes:
        - ./:/usr/src/app
      ports:
        - "3007:3007"
      command: bash -c "npm run test && npm run dev"
